name: tinder_gamer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.2.8+4
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  dio: ^5.2.1+1
  firebase_storage: ^11.2.4
  get: ^4.6.5
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets\images\iconeTinderGamer.png
    - assets\images\GatchWallpaper.png
    - assets\images\GatchIcon.png

  uses-material-design: true
